openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /movie/movie/{movieId}:
    get:
      operationId: getMovie
      tags:
        - Movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /movie/all-movies:
    get:
      operationId: getAllMovies
      tags:
        - Movie
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /movie/movie:
    post:
      operationId: createMovie
      tags:
        - Movie
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
  /movie/{movieId}:
    delete:
      operationId: deleteMovie
      tags:
        - Movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
      responses:
        '204':
          description: ''
components:
  schemas:
    MovieId:
      type: string
    Movie:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MovieId'
        title:
          type: string
        rating:
          type: number
          format: double
          description: The rating scale is one to five stars
      required:
        - id
        - title
        - rating
  securitySchemes: {}